### ISSUE TITLE
coding standards - PSR-2?

### ISSUE THREAD

**Issue by retlehs** [roots/roots#1176]
(this would apply to all PHP projects in the roots org)

**Comment by retlehs** [comment]
yep. just a couple new lines in the editorconfig:

```
[*.php]
indent_size = 4
```

**Comment by retlehs** [comment]
might just use a modified psr-2 ruleset (which would be documented and used on all roots php projects). it would mostly come down to:

* keep 2 spaces instead of switching to 4
* no opening braces on newlines

**Comment by retlehs** [comment]
@JulienMelissas has some wip on https://github.com/JulienMelissas/roots/commits/add-travis but needs help.

**Comment by JulienMelissas** [comment]
Yes, anyone/everyone who wants to work on that or submit PRs, that would be great! I won't be able to get to it until later this week...

**Comment by retlehs** [comment]
closed by #1279
