### ISSUE TITLE
Error running Gulp

### ISSUE THREAD

**Issue by tiborp** [roots/roots#1252]
I know things are not quite ready yet, but I wanted to check out the 8.0 branch anyway. Cloned the branche, ran `npm install` without any problems, but trying the `gulp` command results in an error:

`Error: Error: Cannot find where you keep your Bower packages.` (followed by quite a few file references, mostly from node_modules).

Any help is appreciated!

**Comment by Foxaii** [comment]
Please note that we are asking people to keep general support issues to the [Discourse forum](http://discourse.roots.io/) only. 

Also please understand that we don't have time to support any features or branches yet to be merged. Works in progress are very fluid and what we posted in support today may well be incorrect tomorrow.

Thanks for understanding.

**Comment by austinpray** [comment]
You have to run `bower install`. It can't find the bower packages because they are not there.

**Comment by tiborp** [comment]
Running `bower install` did the trick. I'd say this should be in the readme (for people who're not sure about what they're doing ;-)) Thx!

**Comment by retlehs** [comment]
waiting on @JulienMelissas to update the README. such a slacker

**Comment by JulienMelissas** [comment]
@tiborp, again, the readme will be updated once we're finished with all of these changes (https://github.com/JulienMelissas/roots/commit/0ab0f00d048d797e01cdc1513cb7752571595aed)

**Comment by tiborp** [comment]
Thanks guys. I really appreciate all the work you're doing to get this all going (and helping me out in between!)
