### ISSUE TITLE
[8.0.0] asset revving repeated hashes for `gulp build`

### ISSUE THREAD

**Issue by austinpray** [roots/roots#1266]
If you run "gulp build" instead of "gulp" it keeps re-revving revved files. "gulp build" does not clean up after itself so naturally it will just keep revving until the filename gets too long.

```bash
gulp build --silent && ls dist/scripts
```

```
app-fc8e4f99-fc8e4f99-fc8e4f99-fc8e4f99.js       app.js.map                                       jquery.js                                        modernizr-7cea0221.js
app-fc8e4f99-fc8e4f99-fc8e4f99.js                jquery-8f45edef-8f45edef-8f45edef-8f45edef.js    jquery.js.map                                    modernizr.js
app-fc8e4f99-fc8e4f99.js                         jquery-8f45edef-8f45edef-8f45edef.js             modernizr-7cea0221-7cea0221-7cea0221-7cea0221.js modernizr.js.map
app-fc8e4f99.js                                  jquery-8f45edef-8f45edef.js                      modernizr-7cea0221-7cea0221-7cea0221.js
app.js                                           jquery-8f45edef.js                               modernizr-7cea0221-7cea0221.js
```

This will totally go away when this gets merged: https://github.com/sindresorhus/gulp-rev/pull/77 and we can have revving integrated into each `scripts` `styles` `fonts` task.

In the meantime I am definitely going to try to patch this so it doesn't do ridiculous stuff like this.

**Comment by swalkinshaw** [comment]
https://github.com/sindresorhus/gulp-rev/pull/77 was merged fyi.

**Comment by austinpray** [comment]
Oh cool then I'll just fix it properly then.
