### ISSUE TITLE
'trailing' no longer an option in jshint

### ISSUE THREAD

**Issue by Tidal-Wave** [roots/roots#1275]
Totally not a big deal, and it doesn't seem to be breaking anything or causing any problems, but it seems that 'trailing' is no longer an option for jshint as per https://github.com/jshint/jshint/pull/1554.

Just wanted to make the note. I can make a pull request if you want, but I figured it would be easier to just let y'all handle it since 8.0.0 is being done atm.

**Comment by austinpray** [comment]
ezpz: https://github.com/roots/roots/pull/1276 :)

**Comment by Tidal-Wave** [comment]
:+1:

**Comment by retlehs** [comment]
closed via 09e494683b42bf8f180a1831033003b11d782c40
