### ISSUE TITLE
Add JSCS for contributors to this project

### ISSUE THREAD

**Issue by austinpray** [roots/roots#1277]
https://github.com/jscs-dev/node-jscs

To make @swalkinshaw happy.

Note: do NOT add JSCS to the Sage theme for end-users. That would be annoying as hell for end-users. Add JSCS as an npm script to run against contributions to this repo. That way javascript contributions to this project are consistent. After someone clones down the project they can go hogwild. This will solve the problem of me forgetting to put spaces after my `if` statements :P

**Comment by swalkinshaw** [comment]
:+1:

**Comment by JulienMelissas** [comment]
Also a :+1: from me even though I haven't gotten PHPCS working 100% yet...

**Comment by retlehs** [comment]
closed by #1278
