### ISSUE TITLE
CSS changes are not reflecting

### ISSUE THREAD

**Issue by beingsagir** [roots/roots#1284]
Hi All,

Currently I am working with the latest pull from master branch and after installing all the dependencies it is compiling well but any changes in the file main.less or main.css is not changing the site look.

Is there anything else I should know about..

**Comment by austinpray** [comment]
Are you running the grunt commands?

https://github.com/roots/roots#available-grunt-commands

**Comment by retlehs** [comment]
this isn't the place for support. leave more details on a new thread in discourse.
