### ISSUE TITLE
Hard Refresh

### ISSUE THREAD

**Issue by emaildano** [roots/roots#1287]
Anyone else having issues where live-reload will do a hard refresh on saving LESS or SCSS instead of injecting?

I did a fresh git clone to test the issue and it came up again.

**Comment by retlehs** [comment]
not experiencing that over here, but ref #1285 — livereload is being replaced

**Comment by emaildano** [comment]
Thanks, @retlehs for the follow up. I still haven't found where the issue is coming from but I'm willing to hold out for browserSync.

**Comment by austinpray** [comment]
I have browsersync working here https://github.com/guix77/roots/pull/1 

It's working great so far.

**Comment by emaildano** [comment]
I just did a fresh download of the latest 8.0.0 and it's still doing a hard refresh while editing .LESS files even with browserSync.

I've been trying trying to find something wrong on my end but after testing it on a different machine I get the same results.

Am I the only one with this issue?

**Comment by austinpray** [comment]
Related: http://discourse.roots.io/t/gulpfile-with-browsersync/2834/2

**Comment by austinpray** [comment]
@emaildano confirm if that patch fixes the issue and close this out if it does

**Comment by emaildano** [comment]
@austinpray, sure does. Thanks again! :+1:
