### ISSUE TITLE
gulp styles breaks during watch if there's an error

### ISSUE THREAD

**Issue by retlehs** [roots/roots#1288]
currently during `gulp watch`, any errors during stylesheet compilation are breaking the styles task from running again

**Comment by austinpray** [comment]
https://github.com/plus3network/gulp-less/issues/118

**Comment by retlehs** [comment]
:hankey:

**Comment by austinpray** [comment]
https://github.com/plus3network/gulp-less/issues/118#issuecomment-73943605

**Comment by austinpray** [comment]
ehhhhhhhh https://github.com/plus3network/gulp-less/issues/152
