### ISSUE TITLE
browserSync in Backend

### ISSUE THREAD

**Issue by emaildano** [roots/roots#1298]
Is there anyway to disable browserSync based on the URL? Saving a PHP file while in the backend reloaded my window and I lost all my edits.

The only options I see in this area are for ghostMode.

http://www.browsersync.io/docs/options/#option-ghostMode

**Comment by shakyShane** [comment]
```js
var browserSync = require("browser-sync");

browserSync({
    proxy: "wordpress.dev",
    snippetOptions: {
        ignorePaths: "wp-admin/**"
    }
});
```
https://github.com/shakyShane/browser-sync/issues/415

**Comment by JulienMelissas** [comment]
Thanks @shakyShane for the help!

**Comment by shakyShane** [comment]
![tumblr_m0osrrhqmk1qzcv7no4_250](https://cloud.githubusercontent.com/assets/1643522/5992863/1020a94e-aa33-11e4-8386-fd0b8d4078ee.gif)

**Comment by shakyShane** [comment]
May be relevant for you guys.

https://github.com/BrowserSync/browser-sync/issues/373

**Comment by austinpray** [comment]
@shakyShane oh yes absolutely. Thank you for the heads up.
