### ISSUE TITLE
[8.0.0] Nasty npm install bugs, unable to run gulp

### ISSUE THREAD

**Issue by Tidal-Wave** [roots/roots#1307]
All of the sudden I seem to be having issues with getting 8.0.0 up and running. I don't know if this is an isolated incident on my part or if things are still in flux. 

Pulling down 8.0.0 I run `nom install` and get the following errors:

```
> v8flags@1.0.8 install /Users/eric/Development/wp-dev/www/b2b/htdocs/wp-content/themes/banjos/node_modules/gulp/node_modules/v8flags
> node fetch.js

npm ERR! unpack Could not read data for parseurl@1.3.0
npm ERR! unpack Could not read data for escape-html@1.0.1
 [[B-
> ws@0.5.0 install /Users/eric/Development/wp-dev/www/b2b/htdocs/wp-content/themes/banjos/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN optional dep failed, continuing imagemin-pngquant@4.0.0
npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
 
> fsevents@0.2.1 install /Users/eric/Development/wp-dev/www/b2b/htdocs/wp-content/themes/banjos/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
 
> ws@0.4.31 install /Users/eric/Development/wp-dev/www/b2b/htdocs/wp-content/themes/banjos/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! cb() never called!
```
But it does seem to "finish" though. I use that term loosely because it doesn't straight barf at me and roll back, which I've seen before when I screw something up. 

Once I try to run any gulp commands I get this:

```
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/eric/Development/wp-dev/www/b2b/htdocs/wp-content/themes/banjos/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:15:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Any thoughts?

**Comment by Tidal-Wave** [comment]
Ok, Im going to close this because it seems to be machine specific. I was able to get everything going on a second machine, therefore it's not Sage specific. I am however open to suggestion as to what I have borked on this machine tho. @austinpray?

**Comment by austinpray** [comment]
Hey there bud,

So I just tried this on:

- fresh osx yosemite install: node v0.10.35 npm 1.4.28
- fresh debian wheezy node v0.10.36 npm 1.4.28

Both installed great. [Plus travis has been building this stuff all the live-long day](https://travis-ci.org/roots/roots/builds)

First thing I would try is:

```bash
npm cache clean
rm -r node_modules
npm install
```

Lemme know if that fixes it. Definitely start up a discourse thread if it doesn't.

I recommend installing node with [nvm](https://github.com/creationix/nvm) and avoid using sudo with npm.

**Comment by Tidal-Wave** [comment]
yea `npm cache clean` was the first thing I tried, then I got similar but different errors. Im gonna nuke npm and node on that machine (OS X ML) and try reinstalling with nvm and see if that does anything. 

Something happened and I don't know what, last week I was fine on that machine, today, completely borked. 

If I have anymore issues I will hit you up on discourse. 

Thanks.

**Comment by oompt** [comment]
You can avoid using nvm, and the ``sudo npm <whatever>`` approach by simple supplying a path, as the default is usually `` / `` on OSX. 

So, for example, ``npm cache clean ~/ `` will target your user directory, and avoid the need to sudo in this case (and others like this).
