### ISSUE TITLE
Using Sage 8.0.0 with SASS - How?

### ISSUE THREAD

**Issue by heyalbert** [roots/roots#1310]
How I can use Sage with SASS - there a only LESS Files in the assets folder. Can someone explain me, the new structure/process to use Roots with SASS.

Is there any documentation ready for Roots with Sage 8.0.0?

**Comment by JulienMelissas** [comment]
Hey @heyalbert there's an example in the repo: https://github.com/roots/roots/blob/8.0.0/assets/styles/main.scss.example

Hopefully that gets you started, if not, I think the [Discourse](http://discourse.roots.io) might be a better place for us to help you troubleshoot.

**Comment by retlehs** [comment]
see instructions on https://github.com/roots/roots/pull/1245

this will be covered in the docs
