### ISSUE TITLE
Question: importing dependencies

### ISSUE THREAD

**Issue by drawcard** [roots/roots#1313]
I have had a bit of trouble with the wiredep / bower setup as it will bring in some of my "dependencies": but not all of them. So I've had to manually insert references into manifest.json like so:

```
{
  "dependencies": {
    "main.js": {
      "files": [
        "../bower_components/jPushMenu/js/jPushMenu.js",
        "../bower_components/isotope/dist/isotope.pkgd.js",
        "../bower_components/isotope-packery/packery-mode.pkgd.js",
        "scripts/**/*",
        "scripts/main.js"
      ],
      "main": true
    },

"main.css": {
      "files": [
        "../bower_components/fontawesome/css/font-awesome.css",
        "styles/main.scss"
      ],
      "main": true
    },
```

and then run `gulp build` each time.

It's a bit clunky but it works. Am I doing the right thing generally speaking or do I need to take a closer look at my setup?

**Comment by austinpray** [comment]
Hey @drawcard 

Let's see what's going on here. 

```js
bower install https://github.com/takien/jPushMenu.git\#1.1.1 --save
```

Okay so what is going on here?

![screenshot 2015-02-10 10 27 57](https://cloud.githubusercontent.com/assets/2192970/6131495/036d708e-b112-11e4-8ed5-cc9cb548f5d5.png)

The css and the JS from the bower dependencies are not being included. [So it seems like jPushMenu 1.1.1 does not have a bower.json](https://github.com/takien/jPushMenu/compare/1.1.1...master)

## We have two options

### 1. Overrides

![screenshot 2015-02-10 10 42 15](https://cloud.githubusercontent.com/assets/2192970/6131455/a926ff00-b111-11e4-90f2-0ed3a0243467.png)


### 2. Use a newer version

```bash
bower install --save https://github.com/takien/jPushMenu.git#\1e960b77fb3666434a580eb6980403b049f79355
```

![screenshot 2015-02-10 10 35 10](https://cloud.githubusercontent.com/assets/2192970/6131320/a0f21776-b110-11e4-9ecc-6b83d7353bdc.png)


Success!

## Conclusion

- Operate on bower.json for managing all things bower_components. https://github.com/ck86/main-bower-files#overrides-options
- Let's improve the community. The majority of bower packages are improving but an older/non-maintained packages will make you do extra work. https://github.com/takien/jPushMenu/issues/20

**Comment by austinpray** [comment]
It's worth noting that if push comes to shove:

```json
{
  "dependencies": {
    "main.js": {
      "files": [
        "scripts/**/*",
        "scripts/main.js"
      ],
      "vendor": [
        "bower_components/jPushMenu/js/jPushMenu.js",
        "bower_components/isotope/dist/isotope.pkgd.js",
        "bower_components/isotope-packery/packery-mode.pkgd.js"
      ],
      "main": true
    },
    "main.css": {
      "files": [
        "styles/main.scss"
      ],
      "vendor": [
        "bower_components/fontawesome/css/font-awesome.css"
      ],
      "main": true
    }
  }
}
```

But try to keep bower_components stuff out of manifest.json. Keep all that in bower.json. The package maintainer is the one who should be specifying the main property. The package project file structure is liable to change at any moment. For instance tomorrow with an update they could change their css location to:

```
bower_components/fontawesome/changing/things/up/css/font-awesome.min.css
```

And you would be left doing the detective work as to why your fonts stopped loading.

**Comment by drawcard** [comment]
Thanks very much for that :) 

This worked great for `jPushMenu` but unfortunately not for `isotope` + `isotope-packery`. I had to revert to the ["push comes to shove"](https://github.com/roots/roots/issues/1313#issuecomment-73737657) option to make that work. I agree that's not a perfect solution though.

I'm wondering if this is because isotope needs to be implemented outside of the asset-builder altogether. I don't know for sure as I'm not strong in JS, but from what I read about "undefined" errors, the chain of dependencies on scripts etc. is going awry somewhere and the cart is going before the horse. 

Is there a way that scripts can be put through asset-builder in a particular order? I figured it out with "main" references inside individual packages, but I can't move one entire bower package above another (eg. isotope package before jpushmenu).

Here was my attempt at getting isotope working using your steps outlined in [Option 1](https://github.com/roots/roots/issues/1313#issuecomment-73735184):

bower.json: https://gist.github.com/drawcard/acebacef4b1dcde43414

Screenshot of node output:
![screenshot_491](https://cloud.githubusercontent.com/assets/1435638/6141664/9b36c3fc-b1f8-11e4-985a-7e22ec6de879.png)

Screenshot of browser errors (isotope wouldn't render):
![screenshot_490](https://cloud.githubusercontent.com/assets/1435638/6141509/b408b806-b1f6-11e4-98a5-5794ca0a2ac9.png)

**Comment by austinpray** [comment]
@drawcard Great questions.

>Is there a way that scripts can be put through asset-builder in a particular order? I figured it out with "main" references inside individual packages, but I can't move one entire bower package above another (eg. isotope package before jpushmenu).

Change the order they appear in the bower.json:
https://gist.github.com/austinpray/577730de6f672a1d3585/revisions

The "undefined" error is because you are trying to run the isotope packer _before_ isotope is included. isotope packer extends isotope, so isotope needs to be defined first.

Also as a by-the-way:

```js
{
  "dependencies": {
    "app.js": {
      "main": true, // include bower components
      "vendor": [ // external libs not available via bower
        "vendor/proprietary.js",
        "vendor/third-party-lib.js"
      ],
      "files": [ // first-party code you wrote for this project
        "scripts/services/user.js", 
        "scripts/main.js"
      ]
    }
  }
}
```

This will end up giving you an array of files for app.js that looks like

```json
[
  "bower_components/jquery/jquery.js",
  "vendor/proprietary.js",
  "vendor/third-party-lib.js",
  "assets/scripts/services/user.js", 
  "assets/scripts/main.js"
]
```

So ordering:

1. Bower deps: In the order they appear in your bower.json. Main files in the order they are their respective bower.json
2. Vendor deps: in the order they appear in your manifest.json
3. Project deps (file property): in the order they appear in your manifest.json

Also check out the help: https://github.com/austinpray/asset-builder/tree/master/help and examples https://github.com/austinpray/asset-builder/blob/master/help/examples.md 

I'm trying to add more and more documentation. The more situations I can document the clearer I believe the usage will be. Definitely let me know how else I can improve the instructions, contributions appreciated.

**Comment by drawcard** [comment]
That worked! Thank you so much for your help - I will watch your project and will definately contribute anything I can to it :+1: :beers:

**Comment by austinpray** [comment]
My pleasure! Let me know if I can help further! :beers:

**Comment by drawcard** [comment]
Sorry to reopen this Austin, but I ran a `gulp clean && gulp build` on the project, and I am getting "undefined" errors again for many packages including isotope. However node's output shows that the files should be included in build-asset. I have tried re-ordering them and declaring them manually in `overrides` as a backup, but no luck. The package causing issues is `fullpage.js` and `isotope` itself.

Here's my bower.json gist: https://gist.github.com/drawcard/b76107577f92c0a6c97c

**Comment by drawcard** [comment]
Weird, after a few brower refreshes, `fullpage.js` is showing up, but not isotope. It might be something to do with the `overrides` declaration.

**Comment by drawcard** [comment]
So isotope refuses to add into the asset-builder stream for no good reason, and after trying a `vendor` reference in `manifest.json` and not having that work either, I've given up and have gone back to including them in `files` which seems to be the only solid thing working after `grunt build`:

```json
  "dependencies": {
    "main.js": {
      "files": [
        "../bower_components/isotope/dist/isotope.pkgd.js",
        "../bower_components/isotope-packery/packery-mode.pkgd.js",
        "scripts/**/*",
        "scripts/main.js"
      ],
      "main": true
    },
```
It might be just something odd about this particular package not playing well in the bower.json compile.

I'll probably put this on the backburner for now unless you have any ideas about this. At this point I'm just happy to have isotope loading after hours of tinkering around!

**Comment by austinpray** [comment]
I'll see if I can get isotope working specifically. 

Remember to put them under vendor and not "files". Otherwise they will get jshinted.

**Comment by drawcard** [comment]
Cheers - I really appreciate your help, though I may just go back to Roots 7.x for this particular project, as I need to get it rolled out quickly and I can't spare much more time on learning the ropes for 8.0. I will come back to 8.0 though when there's more documentation & time for me to fully understand the new compile sequence. I'm happy to keep beta testing for you on test projects when the time calls for it!

But thank you again for your efforts in helping me out - you've done a great job of explaining many things and I hope a lot of it will be useful for documentation once you officially roll out 8.0!

**Comment by austinpray** [comment]
> I'm happy to keep beta testing for you on test projects when the time calls for it!

Please do, thank you for the feedback!

**Comment by drawcard** [comment]
I just wanted to report in on this topic again, as I wanted to have another go at using 8.0.0 (mainly to get my head around gulp for this and other projects). I started with a fresh WP install and I went through the Roots 8.0 setup procedure I've documented here: https://gist.github.com/drawcard/14300552d52380de1ef8 (Feel free to incorporate any of this into your own documentation if you want to adapt it.)

I hadn't had any hiccups with theme compilation, as well as adding new Bower resources and pulling their JS / CSS into my theme build. It must have been something to do with my original theme, as I had ported it from 7.x to 8.0 and some cruft must have clogged the pipes. A fresh install and theme setup has worked perfectly, so thanks again to you and the Roots team for your work on this :smile: 

I did note a couple of console errors during the ```npm install``` process, which might be due to my individual server setup, but I thought I'd share here anyway in the hope it might be debuggable in Sage 8.0: https://gist.github.com/drawcard/4e6e4353355921d850d4

Anyway I'm thrilled that 8.0 is working flawlessly so far and I can now consider it useable for client jobs :+1:

**Comment by retlehs** [comment]
nice gist... only problem i see is you're using `nano` instead of `vim`. 

just kiddin'. :smile: looks like some normal messages from the browsersync packages and a warning from the imagemin packages that look fine

**Comment by drawcard** [comment]
Hehe @retlehs - the nano thing is bad habit I have to break :) Good to know I can ignore those messages in the NPM output!

**Comment by austinpray** [comment]
@drawcard good job! :sunglasses: :sunglasses: :sunglasses: 

It's worth noting that these techniques you pick up by working with Sage are not exclusive to Sage. If you can get this npm + bower + gulp asset pipeline working with sage: you can take this exact setup and use it in single page web app, Jekyll site, Magento, wherever. So definitely worthwhile to pick up!

**Comment by drawcard** [comment]
That's what I'd like to do with other projects I work on that aren't WP related. I have a dream of using the Roots process on standard HTML files as well, by removing the WP-centric PHP files and implementing HTML5 Boilerplate. I really love the way Roots organises and handles all these elements, particularly with 8.0 and the asset-builder, so I want to continue that as much as I can elsewhere! Time to get forking...

**Comment by JulienMelissas** [comment]
I actually have a repo that does all the roots stuff without the WP files, just html5bp, but it hasn't been updated to 8.0.0 - it's really not that hard!
