### ISSUE TITLE
templates/comment.php

### ISSUE THREAD

**Issue by oleynikd** [roots/roots#1330]
Hi,
On [http://roots.io/roots-101/#theme-templates](http://roots.io/roots-101/#theme-templates) it is said that there's a **template for a single comment markup**. But I can't find it... How to customize single comment appearance?
Thanks.

**Comment by retlehs** [comment]
sorry, comments stuff got changed and the docs haven't been updated to reflect it yet. see https://discourse.roots.io/t/roots-7-what-happened-to-the-comments-styling/2484
