### ISSUE TITLE
problem with custom post type

### ISSUE THREAD

**Issue by z-avanes** [roots/roots#1339]
hi
when add custom post type function in extras.php get this error but when move function to functions.php it is ok. where is problem?
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'custom_post' not found or invalid function name in /vagrant/wordpress/wp-includes/plugin.php on line 496

**Comment by AdamWills** [comment]
Support issues should be posted here: https://discourse.roots.io/
