### ISSUE TITLE
Conditional check for templates isn't working correctly SAGE

### ISSUE THREAD

**Issue by webgurus** [roots/roots#1345]
Hello,
Completion to my earlier issue:

I am using sage, and I thought I would mention that I might found a bug.

The format in which I define the template list is exactly the format in the example comment.

Marton

**Comment by QWp6t** [comment]
The syntax you used in the other issue is incorrect for both Roots and Sage.

http://discourse.roots.io/

**Comment by Foxaii** [comment]
This stems from `is_page_template` not accepting arrays, which is why we treated it separately from the other conditional checks. You can read about the "The Second Array: Page Templates" in my article on [The Roots Sidebar](http://roots.io/the-roots-sidebar/).
